import { Skill } from "@/lib/schemas";

export const skillsList: Skill[] = [
  // Practical project experience (Tier 1) - Project backed
  {
    name: "PHP",
    group: "languages",
    level: "practical-project",
    evidence: "cv-project",
    confirmed: true,
    projects: ["buildhub", "starfair-training-institute", "sevix-global"],
  },
  {
    name: "Laravel",
    group: "frameworks",
    level: "practical-project",
    evidence: "cv-project",
    confirmed: true,
    projects: ["buildhub", "sevix-global"],
  },
  {
    name: "MySQL",
    group: "data-and-bi",
    level: "practical-project",
    evidence: "cv-project",
    confirmed: true,
    projects: ["buildhub", "starfair-training-institute", "sevix-global"],
  },
  {
    name: "Core PHP",
    group: "languages",
    level: "practical-project",
    evidence: "cv-project",
    confirmed: true,
    projects: ["starfair-training-institute"],
  },
  {
    name: "Filament",
    group: "frameworks",
    level: "practical-project",
    evidence: "owner-statement",
    confirmed: true,
    projects: ["sevix-global"],
  },
  {
    name: "Livewire",
    group: "frameworks",
    level: "practical-project",
    evidence: "owner-statement",
    confirmed: true,
    projects: ["sevix-global"],
  },
  {
    name: "Tailwind CSS",
    group: "frameworks",
    level: "practical-project",
    evidence: "owner-statement",
    confirmed: true,
    projects: ["sevix-global"],
  },
  {
    name: "Alpine.js",
    group: "frameworks",
    level: "practical-project",
    evidence: "owner-statement",
    confirmed: true,
    projects: ["sevix-global"],
  },
  {
    name: "Vite",
    group: "tools",
    level: "practical-project",
    evidence: "owner-statement",
    confirmed: true,
    projects: ["sevix-global"],
  },
  {
    name: "Git & GitHub",
    group: "tools",
    level: "practical-project",
    evidence: "cv-project",
    confirmed: true,
    projects: ["buildhub", "starfair-training-institute"],
  },

  // Broader proficiency (Tier 2) - CV listed
  {
    name: "C",
    group: "languages",
    level: "broader-proficiency",
    evidence: "cv-skills",
    confirmed: true,
  },
  {
    name: "C++",
    group: "languages",
    level: "broader-proficiency",
    evidence: "cv-skills",
    confirmed: true,
  },
  {
    name: "Python",
    group: "languages",
    level: "broader-proficiency",
    evidence: "cv-skills",
    confirmed: true,
  },
  {
    name: "JavaScript",
    group: "languages",
    level: "broader-proficiency",
    evidence: "cv-skills",
    confirmed: true,
  },
  {
    name: "SQL",
    group: "languages",
    level: "broader-proficiency",
    evidence: "cv-skills",
    confirmed: true,
  },
  {
    name: "Flask",
    group: "frameworks",
    level: "broader-proficiency",
    evidence: "cv-skills",
    confirmed: true,
  },
  {
    name: "Django",
    group: "frameworks",
    level: "broader-proficiency",
    evidence: "cv-skills",
    confirmed: true,
  },
  {
    name: "Bootstrap",
    group: "frameworks",
    level: "broader-proficiency",
    evidence: "cv-skills",
    confirmed: true,
  },
  {
    name: "Power BI",
    group: "data-and-bi",
    level: "broader-proficiency",
    evidence: "cv-skills",
    confirmed: true,
  },
  {
    name: "Tableau",
    group: "data-and-bi",
    level: "broader-proficiency",
    evidence: "cv-skills",
    confirmed: true,
  },
  {
    name: "Jupyter Notebook",
    group: "tools",
    level: "broader-proficiency",
    evidence: "cv-skills",
    confirmed: true,
  },
  {
    name: "VS Code",
    group: "tools",
    level: "broader-proficiency",
    evidence: "cv-skills",
    confirmed: true,
  },
  {
    name: "PyCharm",
    group: "tools",
    level: "broader-proficiency",
    evidence: "cv-skills",
    confirmed: true,
  },
];
